# Site settings
title: BloomShape | Customer Analysis Delivered | Dynamic Customer Profiles
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  BloomShape specializes in creating dynamic customer profiles that turn assumption-based personas into validated buyer profiles.
baseurl: ""
url: "http://127.0.0.1:4000/"
#url: "http://www.productbloom.com" # the base hostname & protocol for your site
twitter_username: productbloom

# Build settings
markdown: kramdown
